/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountResponse {
    /// The Account Number. Example: ACC-511274-31364-54
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    /// The region code of the account. Example: US
    #[serde(rename = "regionCode", skip_serializing_if = "Option::is_none")]
    pub region_code: Option<String>,
    /// The name of the account
    #[serde(rename = "accountName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_name: Option<Option<String>>,
    /// Default router config on the account
    #[serde(rename = "defaultRouterConfigId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_router_config_id: Option<Option<String>>,
    /// Default router tls domain on the account
    #[serde(rename = "defaultRouterTlsDomain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_router_tls_domain: Option<Option<String>>,
}

impl AccountResponse {
    pub fn new() -> AccountResponse {
        AccountResponse {
            account_number: None,
            region_code: None,
            account_name: None,
            default_router_config_id: None,
            default_router_tls_domain: None,
        }
    }
}

