/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressResponse {
    /// Reference identifier for address. Example: 55ec6574-10d8-bd9c-1951-d4184f4ae467
    #[serde(rename = "addressReferenceId", skip_serializing_if = "Option::is_none")]
    pub address_reference_id: Option<uuid::Uuid>,
    /// The address lines for the address. Example: 1 Rocket Road
    #[serde(rename = "addressLines", skip_serializing_if = "Option::is_none")]
    pub address_lines: Option<Vec<String>>,
    /// The town/locality of the address. Example: Hawthorne
    #[serde(rename = "locality", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub locality: Option<Option<String>>,
    /// The administrative area of the address. Example: California
    #[serde(rename = "administrativeArea", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub administrative_area: Option<Option<String>>,
    /// The administrative area code of the address. Example: CA
    #[serde(rename = "administrativeAreaCode", skip_serializing_if = "Option::is_none")]
    pub administrative_area_code: Option<String>,
    /// The region of the address. Example: United States
    #[serde(rename = "region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub region: Option<Option<String>>,
    /// The region code of the address. Example: US
    #[serde(rename = "regionCode", skip_serializing_if = "Option::is_none")]
    pub region_code: Option<String>,
    /// The postal code of the address. Example: 90250
    #[serde(rename = "postalCode", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<String>,
    /// Optional field that can be used to store information about the address for external purposes
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<String>>,
    /// A user readable address. Example: 1 Rocket Road, Hawthorne, CA 90250-6844, US
    #[serde(rename = "formattedAddress", skip_serializing_if = "Option::is_none")]
    pub formatted_address: Option<String>,
    /// The latitude of the address: Example 33.92
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// The longitude of the address. Example: -118.32
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
}

impl AddressResponse {
    pub fn new() -> AddressResponse {
        AddressResponse {
            address_reference_id: None,
            address_lines: None,
            locality: None,
            administrative_area: None,
            administrative_area_code: None,
            region: None,
            region_code: None,
            postal_code: None,
            metadata: None,
            formatted_address: None,
            latitude: None,
            longitude: None,
        }
    }
}

