/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressResponseServiceResponse {
    #[serde(rename = "errors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Option<Vec<models::ValidationResult>>>,
    #[serde(rename = "warnings", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Option<Vec<models::ValidationResult>>>,
    #[serde(rename = "information", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub information: Option<Option<Vec<String>>>,
    #[serde(rename = "isValid", skip_serializing_if = "Option::is_none")]
    pub is_valid: Option<bool>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<models::AddressResponse>>,
}

impl AddressResponseServiceResponse {
    pub fn new() -> AddressResponseServiceResponse {
        AddressResponseServiceResponse {
            errors: None,
            warnings: None,
            information: None,
            is_valid: None,
            content: None,
        }
    }
}

