/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AviationMetadataResponse {
    #[serde(rename = "tailNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tail_number: Option<Option<String>>,
    #[serde(rename = "seatCount", skip_serializing_if = "Option::is_none")]
    pub seat_count: Option<i32>,
    #[serde(rename = "airlineIataCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub airline_iata_code: Option<Option<String>>,
    #[serde(rename = "aircraftIataCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub aircraft_iata_code: Option<Option<String>>,
}

impl AviationMetadataResponse {
    pub fn new() -> AviationMetadataResponse {
        AviationMetadataResponse {
            tail_number: None,
            seat_count: None,
            airline_iata_code: None,
            aircraft_iata_code: None,
        }
    }
}

