/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapacityCheckRequest {
    /// The latitude of the address. Example: 33.92
    #[serde(rename = "latitude")]
    pub latitude: f64,
    /// The longitude of the address. Example: -118.32
    #[serde(rename = "longitude")]
    pub longitude: f64,
}

impl CapacityCheckRequest {
    pub fn new(latitude: f64, longitude: f64) -> CapacityCheckRequest {
        CapacityCheckRequest {
            latitude,
            longitude,
        }
    }
}

