/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataUsageOverageLine {
    #[serde(rename = "restricted", skip_serializing_if = "Option::is_none")]
    pub restricted: Option<models::DataBucketType>,
    #[serde(rename = "unrestricted", skip_serializing_if = "Option::is_none")]
    pub unrestricted: Option<models::DataBucketType>,
    #[serde(rename = "pricePerGB", skip_serializing_if = "Option::is_none")]
    pub price_per_gb: Option<f64>,
    #[serde(rename = "usageLimitGB", skip_serializing_if = "Option::is_none")]
    pub usage_limit_gb: Option<f64>,
    #[serde(rename = "overageAmountGB", skip_serializing_if = "Option::is_none")]
    pub overage_amount_gb: Option<f64>,
    #[serde(rename = "consumedAmountGB", skip_serializing_if = "Option::is_none")]
    pub consumed_amount_gb: Option<f64>,
    #[serde(rename = "overagePrice", skip_serializing_if = "Option::is_none")]
    pub overage_price: Option<f64>,
    #[serde(rename = "productId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<Option<String>>,
    #[serde(rename = "dataOverageType", skip_serializing_if = "Option::is_none")]
    pub data_overage_type: Option<models::DataOverageType>,
}

impl DataUsageOverageLine {
    pub fn new() -> DataUsageOverageLine {
        DataUsageOverageLine {
            restricted: None,
            unrestricted: None,
            price_per_gb: None,
            usage_limit_gb: None,
            overage_amount_gb: None,
            consumed_amount_gb: None,
            overage_price: None,
            product_id: None,
            data_overage_type: None,
        }
    }
}

