/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataUsageBillingCycleV2 {
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "dailyDataUsage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub daily_data_usage: Option<Option<Vec<models::DataUsageDailyV2>>>,
    #[serde(rename = "overageLines", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub overage_lines: Option<Option<Vec<models::DataUsageOverageLine>>>,
    #[serde(rename = "dataPoolUsage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_pool_usage: Option<Option<Vec<models::DataPoolUsagePublicResponse>>>,
    #[serde(rename = "totalPriorityGB", skip_serializing_if = "Option::is_none")]
    pub total_priority_gb: Option<f64>,
    #[serde(rename = "totalStandardGB", skip_serializing_if = "Option::is_none")]
    pub total_standard_gb: Option<f64>,
    #[serde(rename = "totalOptInPriorityGB", skip_serializing_if = "Option::is_none")]
    pub total_opt_in_priority_gb: Option<f64>,
    #[serde(rename = "totalNonBillableGB", skip_serializing_if = "Option::is_none")]
    pub total_non_billable_gb: Option<f64>,
}

impl DataUsageBillingCycleV2 {
    pub fn new() -> DataUsageBillingCycleV2 {
        DataUsageBillingCycleV2 {
            start_date: None,
            end_date: None,
            daily_data_usage: None,
            overage_lines: None,
            data_pool_usage: None,
            total_priority_gb: None,
            total_standard_gb: None,
            total_opt_in_priority_gb: None,
            total_non_billable_gb: None,
        }
    }
}

