/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataBlockSummaryResponse {
    /// The block's product id.
    #[serde(rename = "productId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<Option<String>>,
    /// The block's start date.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// The block's end date.
    #[serde(rename = "expirationDate", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    /// How many blocks of this type there are.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The data amount of each block.
    #[serde(rename = "dataAmount", skip_serializing_if = "Option::is_none")]
    pub data_amount: Option<f64>,
    /// The unit that the data amount is in.
    #[serde(rename = "dataUnitType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_unit_type: Option<Option<String>>,
}

impl DataBlockSummaryResponse {
    pub fn new() -> DataBlockSummaryResponse {
        DataBlockSummaryResponse {
            product_id: None,
            start_date: None,
            expiration_date: None,
            count: None,
            data_amount: None,
            data_unit_type: None,
        }
    }
}

