/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataUsageBillingCycle {
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "dataUsage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_usage: Option<Option<Vec<models::DataUsageBin>>>,
    #[serde(rename = "dailyDataUsages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub daily_data_usages: Option<Option<Vec<models::DataUsageDaily>>>,
    #[serde(rename = "overageLines", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub overage_lines: Option<Option<Vec<models::DataUsageOverageLine>>>,
}

impl DataUsageBillingCycle {
    pub fn new() -> DataUsageBillingCycle {
        DataUsageBillingCycle {
            start_date: None,
            end_date: None,
            data_usage: None,
            daily_data_usages: None,
            overage_lines: None,
        }
    }
}

