/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataUsageDailyV2 {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "priorityGB", skip_serializing_if = "Option::is_none")]
    pub priority_gb: Option<f64>,
    #[serde(rename = "optInPriorityGB", skip_serializing_if = "Option::is_none")]
    pub opt_in_priority_gb: Option<f64>,
    #[serde(rename = "standardGB", skip_serializing_if = "Option::is_none")]
    pub standard_gb: Option<f64>,
    #[serde(rename = "nonBillableGB", skip_serializing_if = "Option::is_none")]
    pub non_billable_gb: Option<f64>,
}

impl DataUsageDailyV2 {
    pub fn new() -> DataUsageDailyV2 {
        DataUsageDailyV2 {
            date: None,
            priority_gb: None,
            opt_in_priority_gb: None,
            standard_gb: None,
            non_billable_gb: None,
        }
    }
}

