/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptInPeriodResponse {
    #[serde(rename = "productId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<Option<String>>,
    #[serde(rename = "activatedBySubjectId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub activated_by_subject_id: Option<Option<String>>,
    #[serde(rename = "activatedDate", skip_serializing_if = "Option::is_none")]
    pub activated_date: Option<String>,
    #[serde(rename = "deactivatedBySubjectId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deactivated_by_subject_id: Option<Option<String>>,
    #[serde(rename = "deactivatedDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deactivated_date: Option<Option<String>>,
    #[serde(rename = "isCoolDown")]
    pub is_cool_down: bool,
}

impl OptInPeriodResponse {
    pub fn new(is_cool_down: bool) -> OptInPeriodResponse {
        OptInPeriodResponse {
            product_id: None,
            activated_by_subject_id: None,
            activated_date: None,
            deactivated_by_subject_id: None,
            deactivated_date: None,
            is_cool_down,
        }
    }
}

