/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialPeriodResponse {
    /// The unique product identifier
    #[serde(rename = "productReferenceId", skip_serializing_if = "Option::is_none")]
    pub product_reference_id: Option<String>,
    /// The timestamp of the start of the partial period
    #[serde(rename = "periodStart", skip_serializing_if = "Option::is_none")]
    pub period_start: Option<String>,
    /// The timestamp of the end of the partial period
    #[serde(rename = "periodEnd", skip_serializing_if = "Option::is_none")]
    pub period_end: Option<String>,
}

impl PartialPeriodResponse {
    pub fn new() -> PartialPeriodResponse {
        PartialPeriodResponse {
            product_reference_id: None,
            period_start: None,
            period_end: None,
        }
    }
}

