/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceLineDataUsageForBillingCycles {
    #[serde(rename = "accountNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<Option<String>>,
    #[serde(rename = "serviceLineNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_line_number: Option<Option<String>>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "billingCycles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub billing_cycles: Option<Option<Vec<models::DataUsageBillingCycleV2>>>,
    #[serde(rename = "servicePlan", skip_serializing_if = "Option::is_none")]
    pub service_plan: Option<Box<models::DataServicePlan>>,
    #[serde(rename = "lastUpdated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<Option<String>>,
}

impl ServiceLineDataUsageForBillingCycles {
    pub fn new() -> ServiceLineDataUsageForBillingCycles {
        ServiceLineDataUsageForBillingCycles {
            account_number: None,
            service_line_number: None,
            start_date: None,
            end_date: None,
            billing_cycles: None,
            service_plan: None,
            last_updated: None,
        }
    }
}

