/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionProductResponse {
    /// The unique product identifier
    #[serde(rename = "productReferenceId", skip_serializing_if = "Option::is_none")]
    pub product_reference_id: Option<String>,
    /// Name of the product
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Monthly price
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    /// Currency code for the price
    #[serde(rename = "isoCurrencyCode", skip_serializing_if = "Option::is_none")]
    pub iso_currency_code: Option<String>,
    /// If Product Has SLA
    #[serde(rename = "isSla", skip_serializing_if = "Option::is_none")]
    pub is_sla: Option<bool>,
    /// The maximum number of user terminals that can be assigned to a single service line using this product. Null response means an unlimited number of UTs can be assigned.
    #[serde(rename = "maxNumberOfUserTerminals", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_number_of_user_terminals: Option<Option<i32>>,
    #[serde(rename = "dataProducts", skip_serializing_if = "Option::is_none")]
    pub data_products: Option<Box<models::DataProductsResponse>>,
}

impl SubscriptionProductResponse {
    pub fn new() -> SubscriptionProductResponse {
        SubscriptionProductResponse {
            product_reference_id: None,
            name: None,
            price: None,
            iso_currency_code: None,
            is_sla: None,
            max_number_of_user_terminals: None,
            data_products: None,
        }
    }
}

