/*
 * Starlink Enterprise API
 *
 * <h3>Description</h3>API to manage accounts and user terminals. This page is deprecated, please use the new documentation site: <a href='https://starlink.readme.io/'>https://starlink.readme.io/</a><h3>Authentication - OIDC</h3><p>To authenticate with this API using OIDC, <a target='_blank' href='/api/auth/.well-known/openid-configuration'>Well Known URL</a> and attach the result to your requests with the <strong>Authorize</strong> button below.</p>
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBatchDeviceConfigRequest {
    /// Config id (or none) to assign to specified devices
    #[serde(rename = "configId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config_id: Option<Option<String>>,
    /// Devices to immediately update.
    #[serde(rename = "deviceIds")]
    pub device_ids: Vec<String>,
}

impl UpdateBatchDeviceConfigRequest {
    pub fn new(device_ids: Vec<String>) -> UpdateBatchDeviceConfigRequest {
        UpdateBatchDeviceConfigRequest {
            config_id: None,
            device_ids,
        }
    }
}

